// mockData.js
export const stockData = [
  {
    id: 1,
    productCode: "0244001",
    itemName: "ท่อเหล็กดำ sch 40",
    category: "หมวดหมู่1",
    number: "เบอร์1",
    model: "รุ่นA",
    color: "สีดำ",
    size: "40",
    costPrice: 100,
    storageLocation: "โกดัง1",
    stockStatus: "มีในสต๊อก",
    quantity: 100,
    unit: "เส้น",
  },
  {
    id: 2,
    productCode: "0230301",
    itemName: "ท่อเหล็กดำ sch 30",
    category: "หมวดหมู่1",
    number: "เบอร์2",
    model: "รุ่นB",
    color: "สีดำ",
    size: "30",
    costPrice: 50,
    storageLocation: "โกดัง1",
    stockStatus: "กำลังสั่งซื้อ",
    quantity: 50,
    unit: "เส้น",
  },
  {
    id: 3,
    productCode: "0230302",
    itemName: "ท่อเหล็กดำ sch 20",
    category: "หมวดหมู่2",
    number: "เบอร์3",
    model: "รุ่นC",
    color: "สีดำ",
    size: "20",
    costPrice: 0,
    storageLocation: "โกดัง2",
    stockStatus: "หมด",
    quantity: 0,
    unit: "เส้น",
  },
  {
    id: 4,
    productCode: "0230303",
    itemName: "ท่อเหล็กดำ sch 80",
    category: "หมวดหมู่2",
    number: "เบอร์4",
    model: "รุ่นC",
    color: "สีดำ",
    size: "20",
    costPrice: 0,
    storageLocation: "โกดัง2",
    stockStatus: "มีในสต๊อก",
    quantity: 0,
    unit: "เส้น",
  },
  // เพิ่มข้อมูลเพิ่มเติมตามต้องการ
];
